### ISSUE TITLE
Can you provide a test case?

### ISSUE THREAD

**Issue by Mr-ZhuJun** [YuanSun-XJTU/iComMa#1]
Hello alumni, can you provide a test case?
You can put just a few images （0-10）

├── <model path> 
│   ├── point_cloud   
│   ├── cameras.json
│   ├── cfg_args
│   ├── input.ply

**Comment by YuanSun-XJTU** [comment]
Thank you for your interest in our work. This [link](https://drive.google.com/file/d/1Rg15BpWKCDDW6JYT3l2gHkH4-kzMdbqN/view?usp=sharing ) provides a demo model of the LEGO dataset. You can run it using the following script: `python run.py -m <your path>\icomma_demo\3dgs\lego -s <your path>\icomma_demo\dataset\lego`.
