### ISSUE TITLE
I'd like to know how to compare LightGlue models.

### ISSUE THREAD

**Issue by xiaoc57** [YuanSun-XJTU/iComMa#3]
This is a meaningful job. I am currently studying how to compare camera positioning through the BreadcrumbsHierarchical-Localization library. How do you compare the accuracy of colmap's camera pose? I hope you can provide the code for LightGlue model evaluation.

我近期正在研究如果通过BreadcrumbsHierarchical-Localization库进行相机定位的比较。请问你们是如何对比colmap的相机位姿的准确程度的。我希望你们能够提供LightGlue模型评估的代码。非常感谢~

**Comment by YuanSun-XJTU** [comment]
For matching-based algorithms, the essential matrix is computed using the RANSAC algorithm based on 2D matching points and camera intrinsics to recover the relative camera poses. The code can be referenced from the method implemented in SuperGlue, available [here](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/ddcf11f42e7e0732a0c4607648f9448ea8d73590/models/utils.py#L288).
