### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by LZL-CS** [YuanSun-XJTU/iComMa#4]
Hi @YuanSun-XJTU, thanks for sharing your awesome work. You first trained a 3DGS for a scene, then you still update the parameters of the trained 3DGS during the camera pose estimation (`as requires_grad_(True)`)?
https://github.com/YuanSun-XJTU/iComMa/blob/9b9fb8ae0bba4ffb0911d7f094e5498302a8a931/scene/gaussian_model.py#L249-L254

**Comment by YuanSun-XJTU** [comment]
Hi, thank you for your question. We define an Adam optimizer [here](https://github.com/YuanSun-XJTU/iComMa/blob/9b9fb8ae0bba4ffb0911d7f094e5498302a8a931/run.py#L39). Only the parameters in the `Camera_Pose` class will be updated during backpropagation. The parameters in the `GaussianModel` will not be updated. You can confirm this during debugging by watching its parameters. The issue you mentioned will not affect the final results.
